version: "3.5"

services:

  openvpn:
    image: alekslitvinenk/openvpn
    container_name: openvpn
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn:/opt/Dockovpn_data
    environment:
      HOST_ADDR: "${EXTERNAL_DOMAIN}"
    cap_add:
      - NET_ADMIN

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - pihole:/etc/pihole
    environment:
      TZ: "Europe/Warsaw"
      PIHOLE_DNS_: "unbound"
      DNSMASQ_LISTENING: single
    depends_on:
      - unbound

volumes:
  noip:
  openvpn:
  unbound:
  pihole:
