version: "3.5"

services:

  noip:
    image: mumanski/no-ip:latest
    container_name: noip
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - noip:/config
    environment:
      USERNAME: "${NOIP_USERNAME}"
      PASSWORD: "${NOIP_PASSWORD}"
      DOMAINS: "${EXTERNAL_DOMAIN}"
      INTERVAL: "${NOIP_INTERVAL}"

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      USERID: '1000'
      GROUPID: '1000'
      TZ: "${TIMEZONE}"
    tmpfs:
      - /tmp
    volumes:
      - ${MOUNT_PATH}:/mnt:z
    command: '-s "homeserver;/mnt;yes;no;no;${SAMBA_USERNAME}" -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" -p'

  openvpn:
    image: alekslitvinenk/openvpn
    container_name: openvpn
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn:/opt/Dockovpn_data
    environment:
      HOST_ADDR: "${EXTERNAL_DOMAIN}"
    cap_add:
      - NET_ADMIN

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - unbound:/opt/unbound/etc/unbound/

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: "${TIMEZONE}"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      PIHOLE_DNS_: "unbound;${FALLBACK_DNS}"
      DNSMASQ_LISTENING: single
    depends_on:
      - unbound

volumes:
  noip:
  openvpn:
  unbound:
  pihole:
  pihole_dnsmasq: