version: "3.5"

services:

  noip:
    image: mumanski/no-ip:latest
    container_name: noip
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - no-ip_volume:/config
    environment:
      USERNAME: "${NOIP_USERNAME}"
      PASSWORD: "${NOIP_PASSWORD}"
      DOMAINS: "${NOIP_DOMAINS}"
      INTERVAL: "${NOIP_INTERVAL}"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - pihole_volume:/etc/pihole'
      - pihole_dnsmasq_volume:/etc/dnsmasq.d'
    environment:
      TZ: "Europe/Warsaw"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"

volumes:
  pihole_volume:
  pihole_dnsmasq_volume:
  noip_volume: