version: "3.5"

services:

  noip:
    image: mumanski/no-ip:latest
    container_name: noip
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - noip:/config
    environment:
      USERNAME: "${NOIP_USERNAME}"
      PASSWORD: "${NOIP_PASSWORD}"
      DOMAINS: "${NOIP_DOMAINS}"
      INTERVAL: "${NOIP_INTERVAL}"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: "${GENERAL_TIMEZONE}"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"

  openvpn:
    image: alekslitvinenk/openvpn
    container_name: openvpn
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn:/opt/Dockovpn_data
    environment:
      HOST_ADDR: "${OPENVPN_DOMAIN_ADDRESS}"
    cap_add:
      - NET_ADMIN

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      USERID: '1000'
      GROUPID: '1000'
      TZ: "${GENERAL_TIMEZONE}"
    tmpfs:
      - /tmp
    volumes:
      - ${SAMBA_MOUNT_PATH}:/mnt:z
    command: '-s "homeserver;/mnt;yes;no;no;${SAMBA_USERNAME}" -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" -p'

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea_postgresql
      - default
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea_postgresql:5432
      GITEA__database__NAME: "${GITEA_DB_NAME}"
      GITEA__database__USER: "${GITEA_DB_USER}"
      GITEA__database__PASSWD: "${GITEA_DB_PASSWORD}"
    depends_on:
      - gitea_postgresql

  gitea_postgresql:
    image: postgres:14
    container_name: gitea_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${GITEA_DB_NAME}"
      POSTGRES_USER: "${GITEA_DB_USER}"
      POSTGRES_PASSWORD: "${GITEA_DB_PASSWORD}"
    networks:
      - gitea_postgresql
    volumes:
      - gitea_postgresql:/var/lib/postgresql/data

volumes:
  pihole:
  pihole_dnsmasq:
  noip:
  openvpn:
  gitea:
  gitea_postgresql:

networks:
  gitea_postgresql:
    internal: true