version: "3.5"

services:

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea_postgresql
      - default
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea_postgresql:5432
      GITEA__database__NAME: "${DB_NAME}"
      GITEA__database__USER: "${DB_USER}"
      GITEA__database__PASSWD: "${DB_PASSWORD}"
    depends_on:
      - gitea_postgresql

  gitea_postgresql:
    image: postgres:14
    container_name: gitea_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks:
      - gitea_postgresql
    volumes:
      - gitea_postgresql:/var/lib/postgresql/data

volumes:
  gitea:
  gitea_postgresql:

networks:
  gitea_postgresql:
    internal: true