version: "3.5"

services:

  noip:
    image: mumanski/no-ip:latest
    container_name: noip
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - noip:/config
    environment:
      USERNAME: "${USERNAME}"
      PASSWORD: "${PASSWORD}"
      DOMAINS: "${DOMAINS}"
      INTERVAL: "${INTERVAL}"

volumes:
  noip: