version: "3.5"

services:

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - unbound:/opt/unbound/etc/unbound/

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: "${GENERAL_HOSTNAME}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: "${GENERAL_TIMEZONE}"
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
      FTLCONF_LOCAL_IPV4: "${GENERAL_HOST_IP}"
      PIHOLE_DNS_: "unbound;${PIHOLE_FALLBACK_DNS}"
      DNSMASQ_LISTENING: single
    depends_on:
      - unbound

volumes:
  unbound:
  pihole:
  pihole_dnsmasq: